// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjsabvtcmqezfdueciq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZranNhYnZ0Y21xZXpmZHVlY2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDUzNDgsImV4cCI6MjA3MzY4MTM0OH0.ddrnMKtK1WZ2Oy4HXVpclCTjOk7dXkpXpMBZq1gjnEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});